part of 'home_cubit.dart';
// This file is "main.dart"
// import 'package:freezed_annotation/freezed_annotation.dart';

// // required: associates our `main.dart` with the code generated by Freezed
// part 'home_state.freezed.dart';
// // optional: Since our HomeState class is serializable, we must add this line.
// // But if HomeState was not serializable, we could skip it.
// part 'home_state.g.dart';

@freezed
class HomeState with _$HomeState {
  const factory HomeState({
    @Default([]) List<AuthorModel> result,
    @Default(Status.initial) Status status,
    String? errorMessage,
  }) = _HomeState;
}
