part of 'articles_cubit.dart';


// This file is "main.dart"
// import 'package:freezed_annotation/freezed_annotation.dart';

// // required: associates our `main.dart` with the code generated by Freezed
// part 'articles_state.freezed.dart';
// // optional: Since our ArticleState class is serializable, we must add this line.
// // But if ArticleState was not serializable, we could skip it.
// part 'articles_state.g.dart';

@freezed
class ArticlesState with _$ArticlesState {
  const factory ArticlesState({
    @Default([]) List<ArticleModel> results,
    @Default(Status.initial) Status status,
    String? errorMessage,
  }) = _ArticlesState;
}

